
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class kamoklet1 extends javax.swing.JFrame {
    private DefaultTableModel model = new DefaultTableModel;
    String tgl;
    /**
     * Creates new form kamoklet1
     */
    public kamoklet1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        matarmaja = new javax.swing.JRadioButton();
        doho = new javax.swing.JRadioButton();
        malabar = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        asal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tujuan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kereta Api Moklet");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 10, 150, 40);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 80, 27, 14);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama);
        nama.setBounds(170, 70, 170, 30);

        jLabel5.setText("No ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 120, 27, 14);
        jPanel1.add(id);
        id.setBounds(170, 110, 170, 30);

        jLabel7.setText("Waktu Keberangkatan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(630, 80, 140, 14);

        matarmaja.setBackground(new java.awt.Color(255, 255, 51));
        matarmaja.setText("KA Matarmaja                              16.55");
        jPanel1.add(matarmaja);
        matarmaja.setBounds(480, 160, 230, 23);

        doho.setBackground(new java.awt.Color(255, 255, 51));
        doho.setText("KA Dhoho Penataran                 13.30");
        jPanel1.add(doho);
        doho.setBounds(480, 100, 290, 23);

        malabar.setBackground(new java.awt.Color(255, 255, 51));
        malabar.setText("KA Malabar                                  16.00");
        jPanel1.add(malabar);
        malabar.setBounds(480, 130, 230, 23);

        jLabel8.setText("Nama KA");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 80, 60, 14);

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 220, 70, 30);

        jButton2.setText("Pesan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 220, 70, 30);

        asal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malang" }));
        asal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalActionPerformed(evt);
            }
        });
        jPanel1.add(asal);
        asal.setBounds(170, 200, 170, 30);

        jLabel4.setText("Tanggal Keberangkatan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 170, 114, 14);

        jLabel3.setText("Stasiun Asal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 210, 70, 14);

        tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blitar", "Tulungagung", "Kediri", "Nganjuk" }));
        jPanel1.add(tujuan);
        tujuan.setBounds(170, 240, 170, 30);

        jLabel6.setText("Stasiun Tujuan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 250, 80, 14);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(170, 160, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 290);

        jPanel3.setBackground(new java.awt.Color(102, 255, 51));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 280, 830, 120);

        setBounds(0, 0, 831, 438);
    }// </editor-fold>//GEN-END:initComponents

    private void asalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String Nama = nama.getText();
        String ID = id.getText();
        String Asal = asal.getSelectedItem().toString();
        String Tujuan = tujuan.getSelectedItem().toString();
        String kereta = "";
        
        if(doho.isSelected())
            kereta = "Dhoho Penataran Pukul 13.30";
        else if(malabar.isSelected())
            kereta = "Malabar pukul 16.00";
        else if(matarmaja.isSelected())
            kereta = "Matarmaja pukul 16.55";
        else
            
        if(asal.getSelectedItem()=="Malang"){
        }
        if(tujuan.getSelectedItem()=="Blitar"){
        }
        if(tujuan.getSelectedItem()=="Tulungagung"){
        }
        if(tujuan.getSelectedItem()=="Kediri"){
        }
        if(tujuan.getSelectedItem()=="Nganjuk"){
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kamoklet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kamoklet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kamoklet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kamoklet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kamoklet1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> asal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton doho;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton malabar;
    private javax.swing.JRadioButton matarmaja;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> tujuan;
    // End of variables declaration//GEN-END:variables
}
